[information]
 name = "ring0dark"
 background = "dark"
 author = 'ring0-rootkit'

[palette]
 fg = '#d4d4d4'
 bg = '#181818'

 white = '#ffffff'
 gray = '#545862'
 green = '#73d936'
 red = '#f43841'
 yellow = '#ffdd33'
 brown = '#cc8c3c'

 blue = '#519fdf'
 cyan = '#46a6b2'
 orange = '#c18a56'
 purple = '#b668cd'
 magenta = '#D16D9E'

[highlights]
 Normal = 'fg bg'
 SignColumn = '- bg'
 MsgArea = 'fg bg'
 ModeMsg = 'fg bg'
 MsgSeparator = 'fg bg'
 SpellBad = 'red - u'
 SpellCap = 'yellow - u'
 SpellLocal = 'green - u'
 SpellRare = 'purple - u'
 NormalNC = 'fg bg'
 Pmenu = 'red bg - - 50'
 PmenuSel = '- blue'
 WildMenu = 'fg blue'
 CursorLineNr = 'yellow - b'
 Comment = 'brown - i'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'blue'
 TSAttribute = 'yellow'
 TSConstructor = 'yellow'
 TSType = 'yellow'
